### ISSUE TITLE
"No Response Received" Error

### ISSUE THREAD

**Issue by emmanuel-contreras** [janelia-pypi/mettler_toledo_device_python#4]
Hello,
Thank you so much for making this library available! We are trying to connect a ML303E Mettler Toledo NewClassic MF scale to a computer. The scale is using a serial to USB converter. It is being recognized by the computer but we are getting the following error . I was wondering if you had any suggestions on what may be the problem? 

Thank you

 - Emmanuel

![2016-12-09 13 18 02](https://cloud.githubusercontent.com/assets/14666496/21074169/c8eeda78-beb7-11e6-8565-1f4695d7be90.jpg)

**Comment by rpzatkoff** [comment]
I think the most likely problem is that the scales communication is not set up correctly. The next thing is be thinking about is whether or not you have a working serial adapter with drivers installed..I had some problems with some adapters I tried. I have gotten communication working with windows before but it was early on in my process and I can't remember if there was any weird problems that had to be resolved. 

As far as the communication issues...if your scale has a settings menu make sure the baudrate/parity/other serial settings match the defaults used in this library. or make sure you configure the library to match the scale.  Also if there is a "protocol" option make sure you select "SICS" or "MT-SICS" or something similar to that. FYI in some older model PS60s i had to go through some manuals to find out the Protocol7 was actually the one we needed because they were all unnamed.  If you don't have a settings menu then make sure you have a scale that uses that protocol..because thats what this library assumes.

my setup with the program is (these counting scales)[http://www.mt.com/ca/en/home/products/Industrial_Weighing_Solutions/bench-scales/counting-scale/ICS465.html]

I have (this serial adapter)[https://www.amazon.com/gp/product/B0007T27H8/ref=oh_aui_search_detailpage?ie=UTF8&psc=1]  hooked up to the counting scales.
And the adapter is plugged into a raspberryPI which is where I run the program that leverages this library to communicate with the scales. 

the little program I have exposes access to the scale over a simple rest interface using flask allowing me to connect and get the current weight to the scales from anywhere on our network

**Comment by metalshreds** [comment]
Thank you so much for the reply! We have the same serial adapter in our scale. I'll check to see if I can select "MT-SICS/SICS" on our scale and that we are using the correct protocol. 

We did get the script to work on a separate scale that had a USB output on a raspberry pi, it's just the serial-> usb and Windows setup that isn't working. I will update the ticket if we are able to get it working.

**Comment by rpzatkoff** [comment]
something else to know when interacting with the scales. when you are dealing with a staight usb connection it is a different protocol entirely that the scales use and this library is the one I used for that...https://github.com/ryepdx/pyusb-scale

the usb to serial adapter still acts like an rs232 device to the computer it is hooked up to. and as far as i know the serial device is the only one the sics library is used for

**Comment by metalshreds** [comment]
Interesting, on our other setup, we are using a MS 303S that has a USB connection to the raspberry pi. We used your library on our pi and it worked fine without that USB library you mentioned.  It's possible the raspberry pi is detecting the usb scale as an rs232 device.

https://github.com/emmanuel-contreras/rpi_usb
File: circularBuffer.py

**Comment by rpzatkoff** [comment]
i could be completely wrong. Everything I think I know about this stuff is from my own trial and error.  Good Luck

**Comment by metalshreds** [comment]
No problem! yea if I get any new insight on how these work I'll be sure to share it with you. Thanks again.

**Comment by emmanuel-contreras** [comment]
Quick update,  I found the manual and saw that the settings you specified (MT-SICS, baud rate..etc) are all the default settings so we did a factory reset of the mettler toledo scale ML303E  and it worked!
